#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: <%= Craftery.credentials_config.db.database %>
  pool: 5
  username: <%= Craftery.credentials_config.db.username %>
  password: <%= Craftery.credentials_config.db.password %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= Craftery.credentials_config.db.database %>
  pool: 5
  username: <%= Craftery.credentials_config.db.username %>
  password: <%= Craftery.credentials_config.db.password %>

# TODO: finish credentials config for production database
production:
  adapter: postgresql
  encoding: unicode
  database: <%= Craftery.credentials_config.db.database %>
  pool: 5
  username: <%= Craftery.credentials_config.db.username %>
  password: <%= Craftery.credentials_config.db.password %>
